version: '3.3'
services:
  web:
    image: apap-registry.cs.ui.ac.id/moreno.rassya/tk_tha_24_frontend
    restart: always
    ports:
      - '10155:8080'
    volumes:
      - ./frontend/file-storage:/file-storage
      - ./frontend/log:/log
    env_file:
      - ./frontend/.env
    networks:
      - frontend-network
  catalog:
    image: apap-registry.cs.ui.ac.id/moreno.rassya/tk_tha_24_catalog
    restart: always
    ports:
      - '10154:8083'
    volumes:
      - ./catalog/file-storage:/file-storage
      - ./catalog/log:/log
    env_file:
      - ./catalog/.env
    depends_on:
      - db
    networks:
      - backend-network
  order:
    image: apap-registry.cs.ui.ac.id/moreno.rassya/tk_tha_24_order
    restart: always
    ports:
      - '10153:8082'
    volumes:
      - ./order/file-storage:/file-storage
      - ./order/log:/log
    env_file:
      - ./order/.env
    depends_on:
      - db
    networks:
      - backend-network
  user:
    image: apap-registry.cs.ui.ac.id/moreno.rassya/tk_tha_24_user
    restart: always
    ports:
      - '10152:8081'
    volumes:
      - ./user/file-storage:/file-storage
      - ./user/log:/log
    env_file:
      - ./user/.env
    depends_on:
      - db
    networks:
      - backend-network
  db:
    image: postgres:14-alpine
    ports:
      - '15152:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network
volumes:
  db:
    driver: local
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge